apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: chefmate-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chefmate-frontend
  template:
    metadata:
      labels:
        app: chefmate-frontend
    spec:
      containers:
        - name: frontend
          # IMPORTANTE: Reemplaza con el nombre de la imagen que subas a Docker Hub
          image: jcfernandez20/chefmate-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: chefmate-config
          env:
            - name: PORT
              value: "80"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  # LoadBalancer proveerá una IP externa pública si lo corres en la nube
  type: LoadBalancer
  selector:
    app: chefmate-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
